baseURL: https://www.lukasweissenhorn.com
languageCode: en-US
title: Lukas Weissenhorn
theme: hugo-profile
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS
Paginate: 3
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
params:
  title: Lukas Weissenhorn
  description: Personal page of Lukas Weissenhorn
  favicon: /fav.png
  useBootstrapCDN: false
  animate: true
  theme: null
  font:
    fontSize: 1rem
    fontWeight: 400
    lineHeight: 1.5
    textAlign: left
  navbar:
    align: ms-auto
    brandName: Lukas Weissenhorn
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
  hero:
    enable: true
    intro: 'Hi, my name is'
    title: Lukas.
    subtitle: 'I build software, blog and invest.'
    content: >-
      A passionate developer. I tend to make use of modern web technologies to
      build software that looks great, feels fantastic, and functions correctly.
    image: /images/me.jpeg
    button:
      enable: true
      name: Resume
      url: '#about'
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: 'https://github.com/LuKaS0473'
        - icon: fab fa-twitter
          url: 'https://twitter.com/WeissenhornLuki'
        - icon: fab fa-instagram
          url: 'https://www.instagram.com/weissenhorn.lukas/'
        - icon: fab fa-linkedin
          url: 'https://www.linkedin.com/in/lukas-weissenhorn-31117a260/'
  about:
    enable: true
    title: About Me
    image: /images/me.jpeg
    content: >-
      I am a student and I love programming. I have big plans for my future and
      hope to become a successful businessman, investor, and blogger. I have
      always been interested in using my programming skills to create new
      ventures and make a positive impact on the world. In my free time, I enjoy
      sharing my insights and experiences through my blog. I am determined to
      work hard and achieve my goals, and I believe that with dedication and
      perseverance, I can make my dreams a reality.

      <br><br>
    skills:
      enable: true
      title: 'Here are a few technologies I''ve been working with recently:'
      items:
        - HTML
        - CSS
        - TypeScript
        - Hugo
        - Java
        - Node
  experience:
    enable: true
    items:
      - job: Software Developer
        company: Freelancer
        date: Jan 2023 - Current
        info:
          enable: true
          content: I am working as a freelance software developer.
        content: >
          I am working as a freelance software developer at Vienna, AT.
      - job: Software Developer
        company: Alpin GmbH Srl
        companyUrl: 'https://www.alpin.it/'
        date: May 2022 - Oct 2022
        info:
          enable: true
          content: >-
            I worked as a software developer for four months for "Alpin GmbH
            Srl".
        content: >
          I worked on a new design for ["Digitised stock of the Provincial
          Library Dr. Friedrich
          Teßmann"](https://digital.tessmann.it/tessmannDigital/digitisedJournalsArchive/Search)
          at Bozen, IT. I had to replace the old design with the new design and
          make adjustments.

          <br><br>

          I also programmed several internal company tools, where I had a lot to
          do with databases and online stores.


          - Databases and optimization

          - Redesign of a website
      - job: Junior Software Developer
        company: Energy Evolution
        companyUrl: 'https://www.en-evo.com/'
        date: May 2021 - Oct 2021
        info:
          enable: true
          content: >-
            I worked as a junior software developer for four months for "Energy
            Evolution".
        content: >
          I was working on a tool to calculate electricity prices. My task was
          to design and develop the UI of the software. I also developed smaller
          tools like a database monitor etc.


          - Created and developed a frontend design for a product.

          - Managed server and databases
  education:
    enable: true
    index: false
    items:
      - title: Bachelor of Science in Computer Science
        school:
          name: Technische Universität Wien | TU Wien
          url: 'https://www.tuwien.at'
        date: 2022 - Current
          #GPA: 3.9 out of 5.0
          #content: >-
          #Lorem Ipsum

      - title: High School
        school:
          name: Technologische Fachoberschule Max Valier | TFO Max Valier
          url: 'https://www.tfobz.it'
        GPA: 75 out of 100
        date: 2019 - 2022
        content: >-
          - High school diploma with a major in computer science and telecommunications.

      - title: Work security Certificate
        school:
          name: Twelve hours work security course
        date: 23.03.2020
        content: >-
          Issued by the technological secondary school "Max Valier" at Bozen, IT.

      - title: ECDL Certificate
        school:
          name: ECDL Standard Certificate
          url: 'https://ecdl.berufsschule.bz/'
        date: 11.05.2019
        content: >-
          Demonstrated competencies in
            - ECDL Base
            - IT Security Specialised Level
            - Presentation
            - Online Collaboration

  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: 'https://example.com'
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: 'https://github.com/gurusabarish/hugo-profile'
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: 'https://example.com'

  projects:
    enable: true
    items:
      - title: Personal Website
        content: >-
          My personal website made with [Hugo](https://gohugo.io/) and [Hugo Profile](https://github.com/gurusabarish/hugo-profile)
        image: /images/projects/website.png
        featured:
          name: Demo
          link: 'https://www.lukasweissenhorn.com'
        badges:
          - Hugo
          - Markdown
            #links:
         #- icon: fab fa-github
         #  url: 'https://github.com/gurusabarish/hugo-profile'
         #- icon: fab fa-twitter
         #  url: >-
         #    https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
  contact:
    enable: true
    content: >-
      My inbox is always open. Whether you have a question or just want to say
      hi, I’ll try my best to get back to you!
    email: weissenhorn.lukas@protonmail.com
    btnName: Mail me
  footer:
    recentPosts:
      path: blogs
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: 'https://github.com/LuKaS0473'
      linkedin: 'https://www.linkedin.com/in/lukas-weissenhorn-31117a260/'
      twitter: 'https://twitter.com/WeissenhornLuki'
      instagram: 'https://www.instagram.com/weissenhorn.lukas/'
  listPages:
    disableFeaturedImage: false
